# Generated by Django 4.1.6 on 2023-02-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_remove_appointment_appointment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('9 AM', '9 AM'), ('10 AM', '10 AM'), ('11 AM', '11 AM'), ('1:30 PM', '1:30 PM'), ('2:30 PM', '2:30 PM'), ('3:30 PM', '3:30 PM')], default='9 AM', max_length=10),
        ),
    ]
