# Generated by Django 4.1.6 on 2023-02-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_remove_appointment_notes_appointmentnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='AppointmentNote',
        ),
    ]
