# Generated by Django 4.1.6 on 2023-02-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_appointment_notes_delete_appointmentnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
    ]
