# Generated by Django 4.1.6 on 2023-02-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0008_appointment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(default="Vous n'avez pas encore de notes sur ce rendez-vous"),
        ),
    ]
